# Generated by Django 4.2.5 on 2024-09-24 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='customer_address',
            new_name='CustomerAddress',
        ),
        migrations.RenameModel(
            old_name='customer_authentication',
            new_name='CustomerAuthentication',
        ),
    ]
