# Generated by Django 4.2.5 on 2024-09-25 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0003_customerauthentication_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_authentication.customerauthentication'),
        ),
        migrations.AddField(
            model_name='customerauthentication',
            name='is_customer',
            field=models.BooleanField(default=True),
        ),
    ]
