# Generated by Django 4.2.5 on 2024-09-25 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('user_authentication', '0004_customeraddress_customer_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerAuthentication',
            new_name='CustomerAccounts',
        ),
    ]
