# Generated by Django 4.2.5 on 2024-09-20 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_manager'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Manager',
            new_name='Accounts',
        ),
    ]
