# Generated by Django 4.2.5 on 2024-09-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_rename_manager_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='password',
            field=models.CharField(max_length=10000),
        ),
    ]
