# Generated by Django 4.2.5 on 2024-09-25 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_accounts_is_active_accounts_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
    ]
