# Generated by Django 4.2.5 on 2024-09-25 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_accounts_is_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='is_manager',
            field=models.BooleanField(default=True),
        ),
    ]
