# Generated by Django 4.2.5 on 2024-09-25 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_alter_accounts_is_manager'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accounts',
            new_name='ManagerAccounts',
        ),
    ]
