# Generated by Django 4.2.5 on 2024-09-25 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_rename_accounts_manageraccounts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ManagerAccounts',
            new_name='Manager_Accounts',
        ),
    ]
